Feat/list
prasath003/sample-web pull request #2
Opened 2021-07-27 09:25 UTC by venkatalakshmi499

added list component

2021-07-27 09:29 UTC, prasath003 requested changes

2021-07-27 09:29 UTC, prasath003 commented on packages/list-component/ListComponent.js
> +
Format this lot of gaps are there

2021-07-27 09:40 UTC, venkatalakshmi499 commented on packages/list-component/ListComponent.js
> +
I have formatted the code

2021-08-09 04:22 UTC, prasath003 approved these changes

2021-08-09 04:23 UTC, merged